-- db/baseline/000-schema.sql  (GENERATED by scripts/db/build-baseline.mjs; do not edit by hand)
--
-- Structure only. Every CREATE TABLE from lca_v3-dump-20260708-181808.sql, the last
-- dump of the dev database taken before migrate-009. It is the schema the
-- numbered root migrations (migrate-009 onward) were written against: the
-- tables of lca_v3_drawsql_schema.sql plus database/migrations/002-008 as the
-- dev database actually had them (005 was never applied there; migrate-010
-- re-adds its columns guarded, so either way works).
--
-- Changes from the dump, made by the generator:
--   * AUTO_INCREMENT counters removed.
--   * account.full_name, company, role, use_case, country, onboarded_at removed: no migration
--     created them (audit AUTH-7). migrate-031-account-profile.sql adds them
--     guarded, so a fresh database proves that migration works and databases
--     that already have the columns are left alone.
-- No row data. Reference rows are in 001-reference.sql.
--
-- Apply order for a fresh database: 000-schema.sql, 001-reference.sql, then
-- scripts/db/migrate.mjs (see scripts/db/fresh.mjs and docs/testing/DATABASE_TESTS.md).

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `account` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `account_type` enum('admin','user') COLLATE utf8mb4_unicode_ci DEFAULT 'user',
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_email` (`email`),
  KEY `idx_username` (`username`),
  CONSTRAINT `chk_email_format` CHECK (regexp_like(`email`,_utf8mb4'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `assessment_results` (
  `result_id` int NOT NULL AUTO_INCREMENT,
  `run_id` int NOT NULL,
  `component_id` int NOT NULL,
  `category_id` int NOT NULL,
  `impact_value` decimal(20,10) NOT NULL,
  `unit` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contribution_percentage` decimal(5,2) DEFAULT NULL,
  `calculated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`result_id`),
  KEY `idx_run` (`run_id`),
  KEY `idx_component` (`component_id`),
  KEY `idx_category` (`category_id`),
  CONSTRAINT `assessment_results_ibfk_1` FOREIGN KEY (`run_id`) REFERENCES `assessment_runs` (`run_id`) ON DELETE CASCADE,
  CONSTRAINT `assessment_results_ibfk_2` FOREIGN KEY (`component_id`) REFERENCES `component` (`component_id`) ON DELETE CASCADE,
  CONSTRAINT `assessment_results_ibfk_3` FOREIGN KEY (`category_id`) REFERENCES `impact_categories` (`category_id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `assessment_runs` (
  `run_id` int NOT NULL AUTO_INCREMENT,
  `case_id` int NOT NULL,
  `run_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `run_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `calculation_method` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT 'CML 2001',
  `region_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` enum('running','completed','failed') COLLATE utf8mb4_unicode_ci DEFAULT 'running',
  `error_log` text COLLATE utf8mb4_unicode_ci,
  `executed_by` int NOT NULL,
  PRIMARY KEY (`run_id`),
  KEY `executed_by` (`executed_by`),
  KEY `idx_case` (`case_id`),
  KEY `idx_date` (`run_date`),
  KEY `idx_status` (`status`),
  CONSTRAINT `assessment_runs_ibfk_1` FOREIGN KEY (`case_id`) REFERENCES `case_table` (`case_id`) ON DELETE CASCADE,
  CONSTRAINT `assessment_runs_ibfk_2` FOREIGN KEY (`executed_by`) REFERENCES `account` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `audit_log` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `action_type` enum('create','update','delete','calculate','export') COLLATE utf8mb4_unicode_ci NOT NULL,
  `table_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `record_id` int NOT NULL,
  `old_values` json DEFAULT NULL,
  `new_values` json DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_table` (`table_name`),
  KEY `idx_timestamp` (`timestamp`),
  KEY `idx_action` (`action_type`),
  CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `account` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `case_table` (
  `case_id` int NOT NULL AUTO_INCREMENT,
  `project_id` int NOT NULL,
  `case_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `case_type` enum('base','comparative') COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_case_id` int DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `region_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`case_id`),
  KEY `parent_case_id` (`parent_case_id`),
  KEY `idx_project` (`project_id`),
  KEY `idx_type` (`case_type`),
  CONSTRAINT `case_table_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) ON DELETE CASCADE,
  CONSTRAINT `case_table_ibfk_2` FOREIGN KEY (`parent_case_id`) REFERENCES `case_table` (`case_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `comparison_metadata` (
  `metadata_id` int NOT NULL AUTO_INCREMENT,
  `comparison_id` int NOT NULL,
  `total_cases_compared` int NOT NULL,
  `total_categories_analyzed` int NOT NULL,
  `overall_best_case_id` int DEFAULT NULL,
  `overall_worst_case_id` int DEFAULT NULL,
  `calculation_time_ms` int DEFAULT NULL,
  `assessment_run_ids` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`metadata_id`),
  UNIQUE KEY `comparison_id` (`comparison_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `comparison_results` (
  `result_id` int NOT NULL AUTO_INCREMENT,
  `comparison_id` int NOT NULL,
  `category_id` int NOT NULL,
  `category_name` varchar(255) NOT NULL,
  `case_results` json NOT NULL COMMENT 'Array of case values with deltas',
  `best_case_id` int DEFAULT NULL,
  `worst_case_id` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`result_id`),
  KEY `idx_comparison_id` (`comparison_id`),
  KEY `idx_category_id` (`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `comparison_runs` (
  `comparison_id` int NOT NULL AUTO_INCREMENT,
  `comparison_name` varchar(255) NOT NULL,
  `project_id` int NOT NULL,
  `case_ids` json NOT NULL COMMENT 'Array of case IDs to compare',
  `comparison_type` enum('absolute','relative','delta') DEFAULT 'absolute',
  `base_case_id` int DEFAULT NULL COMMENT 'First case is the baseline',
  `created_by` int NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`comparison_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `component` (
  `component_id` int NOT NULL AUTO_INCREMENT,
  `case_id` int NOT NULL,
  `parent_component_id` int DEFAULT NULL,
  `component_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `component_type` enum('product','machine_line','subprocess','operation','elemental_task') COLLATE utf8mb4_unicode_ci NOT NULL,
  `hierarchy_level` int NOT NULL,
  `quantity` decimal(15,6) DEFAULT '1.000000',
  `unit` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'unit',
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `process_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Descriptive process type for UI display',
  `driver_category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Selected driver category',
  `driver_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Selected primary driver',
  `labor_occupation` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'BLS OEWS code e.g. 51-4121',
  `labor_hours` decimal(10,4) DEFAULT NULL,
  `drivers` json DEFAULT NULL COMMENT 'Array of selected drivers',
  `opex` decimal(15,2) DEFAULT NULL COMMENT 'Total operational expenditure in USD (sum of cost categories or direct entry)',
  `capex` decimal(15,2) DEFAULT NULL COMMENT 'Total capital expenditure in USD',
  `labor_cost` decimal(15,2) DEFAULT NULL COMMENT 'Labor and personnel costs',
  `energy_cost` decimal(15,2) DEFAULT NULL COMMENT 'Energy and utilities costs',
  `transportation_cost` decimal(15,2) DEFAULT NULL COMMENT 'Transportation and logistics costs',
  `material_cost` decimal(15,2) DEFAULT NULL COMMENT 'Raw materials and supplies costs',
  `equipment_cost` decimal(15,2) DEFAULT NULL COMMENT 'Equipment and machinery costs',
  `overhead_cost` decimal(15,2) DEFAULT NULL COMMENT 'Administrative and overhead costs',
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT 'USD' COMMENT 'Currency code (ISO 4217)',
  `cost_allocation_type` enum('manual','calculated','allocated') COLLATE utf8mb4_unicode_ci DEFAULT 'manual' COMMENT 'Indicates how costs were determined: manual (user-entered), calculated (auto-computed), or allocated (from cost pool)',
  PRIMARY KEY (`component_id`),
  KEY `idx_case` (`case_id`),
  KEY `idx_parent` (`parent_component_id`),
  KEY `idx_type` (`component_type`),
  KEY `idx_level` (`hierarchy_level`),
  KEY `idx_component_costs` (`opex`,`capex`),
  KEY `idx_component_currency` (`currency`),
  CONSTRAINT `component_ibfk_1` FOREIGN KEY (`case_id`) REFERENCES `case_table` (`case_id`) ON DELETE CASCADE,
  CONSTRAINT `component_ibfk_2` FOREIGN KEY (`parent_component_id`) REFERENCES `component` (`component_id`) ON DELETE CASCADE,
  CONSTRAINT `component_chk_1` CHECK ((`hierarchy_level` between 1 and 5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cost_rates` (
  `rate_id` int NOT NULL AUTO_INCREMENT,
  `rate_type` enum('labor','electricity','natural_gas','material','transport') COLLATE utf8mb4_unicode_ci NOT NULL,
  `rate_key` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Welder, Electricity, Steel-HR, etc.',
  `region_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'US state code, country code',
  `rate_value` decimal(15,4) NOT NULL,
  `rate_unit` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '$/hr, $/kWh, $/kg',
  `effective_date` date NOT NULL,
  `source` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_series_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fetched_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rate_id`),
  UNIQUE KEY `unique_rate` (`rate_type`,`rate_key`,`region_code`,`effective_date`),
  KEY `idx_type_region` (`rate_type`,`region_code`),
  KEY `idx_effective` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `driver_impact_factors` (
  `factor_id` int NOT NULL AUTO_INCREMENT,
  `substance_id` int NOT NULL,
  `category_id` int NOT NULL,
  `method_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CML 2001',
  `factor_value` decimal(20,10) NOT NULL,
  `unit` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `geographic_scope` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'Global',
  `temporal_scope` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_quality_score` decimal(3,2) DEFAULT NULL,
  `source_reference` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`factor_id`),
  UNIQUE KEY `unique_substance_category_method_region` (`substance_id`,`category_id`,`method_name`,`geographic_scope`),
  KEY `idx_substance` (`substance_id`),
  KEY `idx_category` (`category_id`),
  KEY `idx_method_category` (`method_name`,`category_id`),
  CONSTRAINT `driver_impact_factors_ibfk_1` FOREIGN KEY (`substance_id`) REFERENCES `substances` (`substance_id`) ON DELETE RESTRICT,
  CONSTRAINT `driver_impact_factors_ibfk_2` FOREIGN KEY (`category_id`) REFERENCES `impact_categories` (`category_id`) ON DELETE RESTRICT,
  CONSTRAINT `driver_impact_factors_chk_1` CHECK ((`data_quality_score` between 0 and 5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `flows` (
  `flow_id` int NOT NULL AUTO_INCREMENT,
  `component_id` int NOT NULL,
  `substance_id` int NOT NULL,
  `flow_type` enum('input','output') COLLATE utf8mb4_unicode_ci NOT NULL,
  `quantity` decimal(15,6) NOT NULL,
  `unit` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_driver` tinyint(1) DEFAULT '0',
  `driver_description` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`flow_id`),
  KEY `idx_component` (`component_id`),
  KEY `idx_substance` (`substance_id`),
  KEY `idx_type` (`flow_type`),
  KEY `idx_driver` (`is_driver`),
  CONSTRAINT `flows_ibfk_1` FOREIGN KEY (`component_id`) REFERENCES `component` (`component_id`) ON DELETE CASCADE,
  CONSTRAINT `flows_ibfk_2` FOREIGN KEY (`substance_id`) REFERENCES `substances` (`substance_id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `impact_categories` (
  `category_id` int NOT NULL AUTO_INCREMENT,
  `category_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abbreviation` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`),
  UNIQUE KEY `category_name` (`category_name`),
  KEY `idx_name` (`category_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `integration_log` (
  `log_id` int NOT NULL AUTO_INCREMENT,
  `source` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `records_affected` int DEFAULT '0',
  `executed_by` int DEFAULT NULL,
  `executed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('success','partial','failed') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'success',
  `details` json DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  KEY `idx_source_time` (`source`,`executed_at`),
  KEY `idx_executed_by` (`executed_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `permissions` (
  `permission_id` int NOT NULL AUTO_INCREMENT,
  `permission_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `permission_name` (`permission_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `project` (
  `project_id` int NOT NULL AUTO_INCREMENT,
  `project_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `owner_id` int NOT NULL,
  `is_template` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`),
  KEY `idx_owner` (`owner_id`),
  KEY `idx_created` (`created_at`),
  CONSTRAINT `project_ibfk_1` FOREIGN KEY (`owner_id`) REFERENCES `account` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `project_members` (
  `member_id` int NOT NULL AUTO_INCREMENT,
  `project_id` int NOT NULL,
  `user_id` int NOT NULL,
  `permission_id` int NOT NULL,
  `added_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_id`),
  UNIQUE KEY `unique_project_user` (`project_id`,`user_id`),
  KEY `permission_id` (`permission_id`),
  KEY `idx_project` (`project_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `project_members_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `project` (`project_id`) ON DELETE CASCADE,
  CONSTRAINT `project_members_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `account` (`id`) ON DELETE CASCADE,
  CONSTRAINT `project_members_ibfk_3` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`permission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `substances` (
  `substance_id` int NOT NULL AUTO_INCREMENT,
  `substance_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cas_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `molecular_formula` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `molecular_weight` decimal(12,4) DEFAULT NULL,
  `pubchem_cid` int DEFAULT NULL,
  `hazard_classification` text COLLATE utf8mb4_unicode_ci,
  `iupac_name` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enriched_at` timestamp NULL DEFAULT NULL,
  `category` enum('resource','emission_air','emission_water','emission_soil','waste') COLLATE utf8mb4_unicode_ci NOT NULL,
  `unit` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`substance_id`),
  UNIQUE KEY `substance_name` (`substance_name`),
  KEY `idx_category` (`category`),
  KEY `idx_name` (`substance_name`),
  KEY `idx_pubchem_cid` (`pubchem_cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
