-- migrate-012-epa-fuel-factors.sql  (GENERATED by scripts/sync-epa-factors.mjs)
-- Per-MMBtu CO2e Global Warming factors for ITAC fuels, parsed from the EPA GHG
-- Emission Factors Hub (Table 1) — CO2 + CH4 + N2O combined at IPCC AR5 GWP100.
-- Supersedes the hand-entered CO2-only values in migrate-011. Re-generate on each
-- EPA release: node scripts/sync-epa-factors.mjs <hub.xlsx> > migrate-012-epa-fuel-factors.sql
-- Parsed 4 fuels: Coal, Wood, Fuel Oil, LPG.

DELETE dif FROM driver_impact_factors dif
JOIN substances s ON s.substance_id = dif.substance_id
WHERE s.substance_name IN ('Coal', 'Wood', 'Fuel Oil', 'LPG')
  AND dif.category_id = 1;

INSERT INTO driver_impact_factors
  (substance_id, category_id, method_name, factor_value, unit,
   geographic_scope, source_reference, factor_basis)
SELECT s.substance_id, 1, m.method_name, v.co2e, 'kg CO2 eq / MMBtu', 'Global', v.prov, 'embodied'
FROM (
  SELECT 'Coal' AS name, 94.012 AS co2e, 'EPA GHG Emission Factors Hub, Table 1: Bituminous (CO2 93.28 + CH4 11g + N2O 1.6g /MMBtu → CO2e)' AS prov
  UNION ALL
  SELECT 'Wood' AS name, 94.956 AS co2e, 'EPA GHG Emission Factors Hub, Table 1: Wood and Wood Residuals (CO2 93.8 + CH4 7.2g + N2O 3.6g /MMBtu → CO2e)' AS prov
  UNION ALL
  SELECT 'Fuel Oil' AS name, 74.203 AS co2e, 'EPA GHG Emission Factors Hub, Table 1: Distillate Fuel Oil No. 2 (CO2 73.96 + CH4 3g + N2O 0.6g /MMBtu → CO2e)' AS prov
  UNION ALL
  SELECT 'LPG' AS name, 61.953 AS co2e, 'EPA GHG Emission Factors Hub, Table 1: Liquefied Petroleum Gases (LPG) (CO2 61.71 + CH4 3g + N2O 0.6g /MMBtu → CO2e)' AS prov
) v
JOIN substances s ON s.substance_name = v.name
CROSS JOIN (
  SELECT 'CML 2001' AS method_name
  UNION ALL SELECT 'ReCiPe Midpoint (H)'
  UNION ALL SELECT 'TRACI 2.1'
) m;
