#!/usr/bin/env node
/**
 * TypeScript error ratchet.
 *
 *   node scripts/tsc-ratchet.mjs
 *
 * Runs `tsc --noEmit` and fails if the number of type errors is higher than
 * the number in scripts/tsc-baseline.txt. `next build` skips type checking
 * (typescript.ignoreBuildErrors), so this is what stops new type errors from
 * landing while the existing ones are paid down. When the count drops, lower
 * the baseline in the same PR so the improvement is locked in; never raise it.
 *
 * Errors in `.next/types/**` are listed but not counted. Those files are
 * generated by `next build`, so they exist locally after a build but not in
 * CI, where this runs before the build; counting them would make the result
 * depend on whether you built first.
 */
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const baselineFile = path.join(root, 'scripts', 'tsc-baseline.txt');

const baseline = Number.parseInt(readFileSync(baselineFile, 'utf8').trim(), 10);
if (!Number.isInteger(baseline) || baseline < 0) {
  console.error(`tsc-ratchet: ${path.relative(root, baselineFile)} must contain a non-negative integer.`);
  process.exit(2);
}

const require = createRequire(import.meta.url);
const tscBin = require.resolve('typescript/bin/tsc');
const result = spawnSync(process.execPath, [tscBin, '--noEmit', '-p', path.join(root, 'tsconfig.json')], {
  cwd: root,
  encoding: 'utf8',
  maxBuffer: 64 * 1024 * 1024,
});
if (result.error) {
  console.error('tsc-ratchet: could not run tsc:', result.error.message);
  process.exit(2);
}

const output = `${result.stdout ?? ''}${result.stderr ?? ''}`;
const errorLines = output.split('\n').filter((line) => /error TS\d+:/.test(line));
const generated = errorLines.filter((line) => line.startsWith('.next/'));
const counted = errorLines.filter((line) => !line.startsWith('.next/'));

if (errorLines.length === 0 && result.status !== 0) {
  // tsc failed without reporting type errors (bad config, crash): surface it.
  console.error(output);
  console.error(`tsc-ratchet: tsc exited with status ${result.status}.`);
  process.exit(result.status || 1);
}

if (generated.length > 0) {
  console.log(`tsc-ratchet: ${generated.length} error(s) in generated .next/types (not counted; they appear only after next build):`);
  for (const line of generated) console.log(`  ${line}`);
}

console.log(`tsc-ratchet: ${counted.length} type error(s); baseline is ${baseline}.`);

if (counted.length > baseline) {
  console.error('');
  for (const line of counted) console.error(line);
  console.error('');
  console.error(
    `tsc-ratchet: type errors rose from ${baseline} to ${counted.length}. ` +
      'Fix the new errors (run `npx tsc --noEmit` for full detail); do not raise the baseline.',
  );
  process.exit(1);
}

if (counted.length < baseline) {
  console.log(
    `tsc-ratchet: below baseline. Set scripts/tsc-baseline.txt to ${counted.length} in this change to lock in the improvement.`,
  );
}
