"""Build migrate-015 (US EPA TRACI 2.1 characterization factors) from the
lciafmt / Federal LCA Commons parquet.

Source (CC0 / US-EPA public domain):
  https://dmap-data-commons-ord.s3.amazonaws.com/lciafmt/traci/TRACI_2.1_v1.0.0_5555779.parquet

Usage:
  python -m venv .venv && .venv/bin/pip install pandas pyarrow
  .venv/bin/python scripts/factor-import/build_traci_sql.py TRACI_2.1.parquet \
      > migrate-015-traci-lciafmt-factors.sql

Crosswalk: TRACI indicator -> LCAPIX impact category, matched by NAME so the
SQL never depends on category ids being equal between databases. One factor
per (flowable, category): a flowable repeats across emission sub-compartments
with the same value, and the base 'emission/air' row wins when present.
Factors outside DECIMAL(20,10) are skipped. TRACI 'Human health - cancer' and
'Human health - particulate matter' have no LCAPIX category yet, so they are
left out (non-cancer maps to Human Toxicity). Every row is basis 'elementary':
these factors characterize emissions, i.e. OUTPUT flows.
"""
import math
import sys

import pandas as pd

CROSSWALK = {
    'Global warming': 'Global Warming',
    'Ozone depletion': 'Ozone Depletion',
    'Acidification': 'Acidification',
    'Eutrophication': 'Eutrophication',
    'Smog formation': 'Photochemical Oxidation',
    'Freshwater ecotoxicity': 'Ecotoxicity',
    'Human health - non-cancer': 'Human Toxicity',
}
SOURCE = 'lciafmt TRACI 2.1 (US EPA, public domain)'


def compartment(ctx):
    c = str(ctx).lower()
    if c.startswith('emission/water'):
        return 'emission_water'
    if 'soil' in c:
        return 'emission_soil'
    if c.startswith('resource'):
        return 'resource'
    return 'emission_air'


def ok(v):
    try:
        v = float(v)
    except (TypeError, ValueError):
        return False
    return math.isfinite(v) and abs(v) < 1e10


def esc(s):
    return str(s).replace('\\', '\\\\').replace("'", "''")


def main(path):
    df = pd.read_parquet(path)
    df = df[df['Indicator'].isin(CROSSWALK)].copy()
    df['category'] = df['Indicator'].map(CROSSWALK)
    df['rank'] = (df['Context'].astype(str) != 'emission/air').astype(int)
    df = df.sort_values(['Flowable', 'category', 'rank'])
    fac = df.drop_duplicates(subset=['Flowable', 'category'], keep='first')
    fac = fac[fac['Characterization Factor'].map(ok)]
    fac = fac[fac['Flowable'].astype(str).str.strip().ne('')]

    subs = {}
    for _, r in fac.iterrows():
        name = str(r['Flowable']).strip()
        cas = str(r['CAS No']).strip()
        cas = cas if cas and cas.lower() != 'nan' else None
        if name not in subs or (subs[name][0] is None and cas):
            subs[name] = (cas, compartment(r['Context']))

    out = [
        '-- migrate-015-traci-lciafmt-factors.sql  (idempotent; generated by scripts/factor-import/build_traci_sql.py)',
        f'-- {len(subs)} substances, {len(fac)} TRACI 2.1 factors. Source: {SOURCE}.',
        '-- Run migrate-017 afterwards (synonyms + unit quarantine).',
    ]
    vals = [
        f"('{esc(n)}',{'NULL' if not c else chr(39) + esc(c) + chr(39)},'{k}','kg')"
        for n, (c, k) in subs.items()
    ]
    for i in range(0, len(vals), 400):
        out.append(
            'INSERT IGNORE INTO substances (substance_name,cas_number,category,unit) VALUES\n'
            + ',\n'.join(vals[i:i + 400]) + ';'
        )
    for _, r in fac.iterrows():
        out.append(
            'INSERT INTO driver_impact_factors (substance_id,category_id,method_name,factor_value,unit,'
            'geographic_scope,factor_basis,source_reference) '
            f"SELECT s.substance_id, ic.category_id, 'TRACI 2.1', {float(r['Characterization Factor']):.10f}, "
            f"'{esc(str(r['Indicator unit']).strip())}', 'Global', 'elementary', '{esc(SOURCE)}' "
            f"FROM substances s JOIN impact_categories ic ON ic.category_name = '{esc(r['category'])}' "
            f"WHERE s.substance_name = '{esc(str(r['Flowable']).strip())}' "
            'ON DUPLICATE KEY UPDATE factor_value=VALUES(factor_value),unit=VALUES(unit),'
            'factor_basis=VALUES(factor_basis),source_reference=VALUES(source_reference);'
        )
    print('\n'.join(out))


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'traci.parquet')
