"""Build migrate-016 (embodied cradle-to-gate material factors, Global Warming only).

Public cradle-to-gate averages (kg CO2-eq per kg of material). Each row's
source_reference names the publisher, document, table, the value as printed and
the per-kg conversion, so a student can check it. Sourced 2026-09-15; the full
notes (scope, recycled content, what could not be verified) are in
research/material-factor-citations-2026-09-15.md. ICE was excluded on license
grounds (its free edition bars use inside software).

Education-grade, NOT certified: multi-category material factors should come from
full EN 15804 EPDs later. Written under all three methods so a BOM material has a
GWP100 factor whichever method a run uses. Basis is 'embodied': these
characterize INPUT flows (material you buy). Scope is 'Global' because it is the
only average on file; the US-data rows say so in their source text.

Usage:
  python scripts/factor-import/build_materials_sql.py > migrate-016-embodied-materials.sql
"""

WARM = 'US EPA WARM v16 (Dec 2023)'
WARM_RMAM = 'raw material acquisition + manufacturing, current mix, US'
ICA = 'International Copper Association et al., Copper and Copper Alloy Semi-Fabricated Products LCA (2019-21 data)'

MATERIALS = [
    ('Steel', 1.9, 'worldsteel 2022 global average crude steel'),
    ('Stainless Steel', 6.15, 'ISSF stainless steel LCI'),
    ('Cast Iron', 1.9, 'worldsteel (cast iron representative)'),
    ('Aluminum', 8.6, 'International Aluminium Institute 2019 (incl. recycled avg)'),
    ('Copper', 3.0, 'International Copper Association'),
    ('Zinc', 3.0, 'International Zinc Association'),
    ('Brass', 1.061,
     f'{ICA}, Table 3 brass rod/bar, global: 1,061 kg CO2e/t (EF 3.0) = 1.061 kg/kg'),
    ('Brass, flat-rolled', 2.855,
     f'{ICA}, Table 6 brass flat-rolled, global: 2,855 kg CO2e/t (EF 3.0) = 2.855 kg/kg'),
    ('Rubber', 2.85, 'PlasticsEurope/ETRMA representative'),
    ('Plastic', 2.5, 'PlasticsEurope average polymer'),
    ('PET', 2.7, 'PlasticsEurope eco-profile'),
    ('HDPE', 1.9, 'PlasticsEurope eco-profile'),
    ('PVC', 2.0, 'PlasticsEurope eco-profile'),
    ('Polypropylene', 1.9, 'PlasticsEurope eco-profile'),
    ('ABS', 3.1, 'PlasticsEurope eco-profile'),
    ('Glass', 0.584,
     f'{WARM}, Exhibit 1-9 glass containers, {WARM_RMAM}: 0.53 MTCO2E/short ton = 0.584 kg/kg'),
    ('Glass, flat', 1.43,
     'NGA industry-average EPD ASTM-EPD121 (2019; expired 2024-12-20, newest US industry average), '
     'Table 5 flat glass A1-A3: 1,430 kg CO2e/t (TRACI 2.1) = 1.43 kg/kg'),
    ('Cardboard', 0.937,
     f'{WARM}, Exhibit 3-11 corrugated containers, {WARM_RMAM}: 0.85 MTCO2E/short ton = 0.937 kg/kg'),
    ('Paper', 1.091,
     f'{WARM}, Exhibit 3-11 office paper, {WARM_RMAM}: 0.99 MTCO2E/short ton = 1.091 kg/kg'),
    ('Wood', 0.187,
     f'{WARM}, Exhibit 12-5 dimensional lumber, raw material acquisition + manufacturing, '
     'forest carbon storage excluded, US: 0.17 MTCO2E/short ton = 0.187 kg/kg'),
    ('Concrete', 0.133,
     'NRMCA industry-average LCA v3.2 (Athena, Dec 2021; EPD expired 2026-03-31, newest found), '
     'Table F1 4000 psi A1-A3: 308.17 kg CO2e/m3 / 2,310.8 kg/m3 (Table B1 mix mass) = 0.133 kg/kg'),
    ('Electronics', 22.9,
     f'{WARM}, Exhibit 1-7 mixed electronics (excl. CRT), manufacturing, US: 20.79 MTCO2E/short ton '
     '= 22.9 kg/kg; product types range 8.4 to 32.9'),
    ('Printed circuit board', 139.7,
     f'{WARM}, Exhibit 1-8 printed circuit board component, manufacturing, US: '
     '126.70 MTCO2E/short ton = 139.7 kg/kg'),
]
METHODS = ('CML 2001', 'TRACI 2.1', 'ReCiPe Midpoint (H)')


def esc(s):
    return s.replace("'", "''")


def main():
    out = [
        '-- migrate-016-embodied-materials.sql  (idempotent; generated by scripts/factor-import/build_materials_sql.py)',
        f'-- {len(MATERIALS)} materials x {len(METHODS)} methods, Global Warming, basis embodied.',
        'INSERT IGNORE INTO substances (substance_name,category,unit) VALUES\n'
        + ',\n'.join(f"('{esc(n)}','resource','kg')" for n, _, _ in MATERIALS) + ';',
    ]
    for name, value, src in MATERIALS:
        for method in METHODS:
            out.append(
                'INSERT INTO driver_impact_factors (substance_id,category_id,method_name,factor_value,unit,'
                'geographic_scope,factor_basis,source_reference) '
                f"SELECT s.substance_id, ic.category_id, '{method}', {value}, 'kg CO2 eq', 'Global', 'embodied', "
                f"'{esc(src)}' FROM substances s JOIN impact_categories ic ON ic.category_name = 'Global Warming' "
                f"WHERE s.substance_name = '{esc(name)}' "
                "ON DUPLICATE KEY UPDATE factor_value=VALUES(factor_value),factor_basis='embodied',"
                'source_reference=VALUES(source_reference);'
            )
    print('\n'.join(out))


if __name__ == '__main__':
    main()
